#  test1 Web App Auto Deployment

image: node:14.0

pipelines:
  branches: # Pipelines triggers on code push in branch
    master:
      - step:
          name: Build
          script:
            - rm -rf node_modules
            - npm install
            # - cp .env.prod .env
            # - cp public/DEV.htaccess public/.htaccess
            - unset CI
           # - echo $ENV_PROD_BASE64 | base64 --decode --ignore-garbage > .env.production
            - npm run build
            - mkdir packaged
            - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
          artifacts:
            - packaged/**
      - step:
          name: Deploy
          image: alpine
          deployment: production
          script:
            - mkdir upload
            - tar -xf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C upload

            - apk update && apk add openssh rsync
            - ssh-keyscan -H $SERVER_ADDRESS >> ~/.ssh/known_hosts
            - rsync -a -e "ssh -o StrictHostKeyChecking=no" --delete upload/ $SERVER_USER@$SERVER_ADDRESS:/tmp/web_admin_${BITBUCKET_BUILD_NUMBER}

            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_ADDRESS "rm -r /var/www/html/*"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_ADDRESS "mv '/tmp/web_admin_${BITBUCKET_BUILD_NUMBER}'/* '/var/www/html/testdeploy'"
